---
name: demo
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  go_router: ^14.2.3
  dartz: ^0.10.1
  dio: ^5.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/
